### ISSUE TITLE
Initialising dropdown's selected item to a default item

### ISSUE THREAD

**Issue by rachel-barrett** [PaackEng/elm-ui-dropdown#23]
Hi,

I haven't been able to find a way to initialize the dropdown to a default value.
Is this something that can be added, and a feature anyone else would be interested in?

Rachel

**Comment by jouderianjr** [comment]
Hello @rachel-barrett, unfortunately, we currently do not provide this feature, but it totally makes sense to add it. Is this something you would like to make a pr or something like that?

Many thanks for the feedback

**Comment by rachel-barrett** [comment]
Hi @jouderianjr. Thanks for your message. Ok great, I’m happy to have a go at a pr for this.  It would be my first time contributing to open source - do I have to think about whether the pr involves breaking changes and therefore what the version bump should be etc? How does a release get triggered? Thanks, Rachel

**Comment by rachel-barrett** [comment]
Created a pull request for this issue here https://github.com/PaackEng/elm-ui-dropdown/pull/24

**Comment by jouderianjr** [comment]
Hey @rachel-barrett many thanks for the pull request, I will check it out this weekend ok? 🎉

**Comment by rachel-barrett** [comment]
Thanks!

**Comment by rachel-barrett** [comment]
No problem, thanks also for your reviews! Totally makes sense to make sure the api is right for the next release. Since it's related to my change and a quick change, I'm happy to create a follow up PR for the change to the options argument probably sometime this week... if that would help?

**Comment by jouderianjr** [comment]
@rachel-barrett it will be great, I really appreciate 👏 👏  Many thanks for the hard work
