### ISSUE TITLE
Picked option to Nothing

### ISSUE THREAD

**Issue by mihkell** [PaackEng/elm-ui-dropdown#26]
How do you make it send OptionPicked as Nothing? The prompt item goes a way when I make a selection. How to leave it in so when it's selected the option picked would send the messages with Nothing?

**Comment by jouderianjr** [comment]
Hello @mihkell this is actually not possible right now, but this will be fixed in the next release. I will let you know once we have this feature enabled!

**Comment by jouderianjr** [comment]
@mihkell this should be possible in the latest release (3.0.0). Let me know if you have any other problems.
