### ISSUE TITLE
Setting a padding on container makes the dropdown item text behave weird

### ISSUE THREAD

**Issue by segmentationfaulter** [PaackEng/elm-ui-dropdown#28]
I am attaching the screenshot showing how the text in the dropdown items go haywire if padding is set on the container.

![Screen Shot 2021-03-25 at 18 03 26](https://user-images.githubusercontent.com/6733537/112487865-e322f400-8d9e-11eb-8558-4253d0af252e.png)

You can see the code resulting into the above screen here.

https://ellie-app.com/cJDLSxGJtnka1

Removing the padding from the container fixes it.

**Comment by jouderianjr** [comment]
This was fixed in the latest release (3.0.0) :D  Thanks
