### ISSUE TITLE
[Feature Request] Ability to set default selected option

### ISSUE THREAD

**Issue by peteygao** [PaackEng/elm-ui-dropdown#30]
Right now the selection always defaults to nothing. I would like to be able to set an initial state when I'm fetching data from the backend and are displaying it on the front-end.

Right now I'm "hacking" around this by changing the default prompt with the pre-set value, but this feels a bit weird PLUS the open dropdown will not have the "selected" option highlighted with the chosen highlight colour.

Is this a first class feature you folks are willing to add to the package?

**Comment by jouderianjr** [comment]
Hey @peteygao, we will have this in the next release,  sadly, this version will have an API change, so it will require some change in the code :'(. We added are able to have this feature after #24 and I just did a proposal for a small change in #31, once we close or merge this pr we will release a new version. Let us know if those changes are good enough for your needs.

**Comment by peteygao** [comment]
Just look at those two PR's, the changes LGTM 👍🏼!

**Comment by jouderianjr** [comment]
This was fixed on 3.0.0
